apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: service
spec:
  taints:
    - key: service
      value: "true"
      effect: NoSchedule
  labels:
    nodeType: service-2022
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["m6i.2xlarge","c6i.2xlarge"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: [ "ap-northeast-2a", "ap-northeast-2c" ]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
  providerRef:
    name: enable-ipvs-service
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 1209600
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: enable-ipvs-service
spec:
  subnetSelector:
    karpenter.sh/discovery/nessa-cluster: '*'
  securityGroupSelector:
    aws:eks:cluster-name: "nessa-cluster"
  instanceProfile: KarpenterNodeInstanceProfile-nessa-cluster
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi
        volumeType: gp3
        iops: 3000
        deleteOnTermination: true
        throughput: 125
  tags:
    service: service
  userData: |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="BOUNDARY"

    --BOUNDARY
    Content-Type: text/x-shellscript; charset="us-ascii"

    #!/bin/bash
    sudo yum install -y ipvsadm
    sudo ipvsadm -l
    sudo modprobe ip_vs
    sudo modprobe ip_vs_rr
    sudo modprobe ip_vs_wrr
    sudo modprobe ip_vs_sh
    sudo modprobe nf_conntrack_ipv4

    --BOUNDARY--
